### ISSUE TITLE
Your Code is not working for me.

### ISSUE THREAD

**Issue by alikazmi181293** [neoighodaro/laravel-pusher-web-notifications#2]
I have just cloned your project setup all the pusher configurations but the notification is not send. The notification bell is also not displaying.

**Comment by rampun** [comment]
@alikazmi181293  Please check the app preview.
The notification bell is displayed only if you have at least 1 notification.
Further, you need to add a cluster to Pusher instance.

Please check 
welcome.blade.php (line: 75)
var pusher = new Pusher('app_key', 
{
 cluster: 'CLUSTER', // this is the issue
 encrypted: true,
});
